#! /usr/bin/env bash

# list all S3 files keep file names only
aws s3 ls s3://$BUCKET_PATH | rev | cut -d' ' -f 1 | rev

# get S3 bucket size with AWS CLI
aws s3 ls s3://my_bucket/ --recursive --human-readable --summarize | tail -2

